heat_template_version: 2015-04-30

description: Sample template to deploy VNF stack with affinity/anti-affinity policies

resources:
  low-latency-vnfs:
    type: OS::Nova::ServerGroup
    properties:
      name: "low-latency-vnfs"
      policies: [affinity]
  
  ha-vnfs: 
    type: OS::Nova::ServerGroup
    properties:
      name: "ha-vnfs"
      policies: [anti-affinity]

  web:
    type: OS::Nova::Server
    properties:
      image: ubuntu-14.04-server-amd64
      flavor: m1.medium
      scheduler_hints: { group: { get_resource: low-latency-vnfs } }
  
  app:
    type: OS::Nova::Server
    properties:
      image: ubuntu-14.04-server-amd64
      flavor: m1.medium
      scheduler_hints: { group: { get_resource: low-latency-vnfs } }
  
  db:
    type: OS::Nova::Server
    properties:
      image: ubuntu-14.04-server-amd64
      flavor: m1.medium
      scheduler_hints: { group: { get_resource: low-latency-vnfs } }
      
  controller01:
    type: OS::Nova::Server
    properties:
      image: ubuntu-14.04-server-amd64
      flavor: m1.medium
      scheduler_hints: { group: { get_resource: ha-vnfs } }
  
  controller02:
    type: OS::Nova::Server
    properties:
      image: ubuntu-14.04-server-amd64
      flavor: m1.medium
      scheduler_hints: { group: { get_resource: ha-vnfs } }
